function Hd = bandpassfilter(Fs, Fc, Fw)
%UNTITLED2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 09-Jun-2015 21:41:52

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

Fpass1 = Fc - Fw/2;   % First Passband Frequency
Fpass2 = Fc + Fw/2;   % Second Passband Frequency
Fstop1 = Fpass1 - 10; % First Stopband Frequency
Fstop2 = Fpass2 + 10; % Second Stopband Frequency
Astop1 = 160;         % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 160;         % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
